### ISSUE TITLE
artifacts in generated images

### ISSUE THREAD

**Issue by hanshengchiu** [masoudpz/AVID-Adversarial-Visual-Irregularity-Detection#3]
I've trained the model for 40 epochs. The generated image shows some weird artifacts as shown below. What could be wrong? I did not modify the model.
![fake_samples-40-300](https://user-images.githubusercontent.com/17819084/70986410-c8bc8e00-20f8-11ea-987c-a4d8bb16952a.png)

**Comment by masoudpz** [comment]
I've seen this before,probably it's for image borders. Try with more epochs it should be fade

**Comment by hanshengchiu** [comment]
It appeared in the middle columns of image too. May I ask how many epochs
did you train? In your code the default value is 40.

**Comment by masoudpz** [comment]
I think it was 90.

**Comment by hanshengchiu** [comment]
After training it for 90 epochs, the artifacts diminished somehow.
However, the generator is also able to reconstruct digit '3' well.

**Comment by masoudpz** [comment]
through this result the best epoch is between 40 and 90.
thanks for sharing your experiences.
