### ISSUE TITLE
Some parts of the data_loader.py need to be modified

### ISSUE THREAD

**Issue by bomtorazek** [masoudpz/AVID-Adversarial-Visual-Irregularity-Detection#4]
For the snippet,
        transforms.Normalize((0.5,0.5,0.5), (0.5,0.5,0.5)),
it should be changed for the images with gray scale like below.

transforms.Normalize((0.5,), (0.5,)),

**Comment by masoudpz** [comment]
of course it is.
Thanks Dear friend for you guidance. you can fork our code and edit it
whatever you eant
